"use client";
import Link from "next/link";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowRight, Check, ChevronDown } from "lucide-react";
import { FaGithub } from "react-icons/fa";
import { useState } from "react";
import BrandLogo from "@/app/components/BrandLogo";
import { Eyebrow, PrimaryCta, Reveal } from "./shared";
import styles from "@/app/landing.module.css";
const faqs=[["Is CalStory free?","Yes. Core meal logging, macro targets, workouts, weight trends, and the progress dashboard are free. Paid plans add higher AI limits and advanced adaptive insights."],["How does adaptive TDEE work?","CalStory starts with an estimated expenditure, then compares your logged intake with your rolling weight trend. As enough data accumulates, it adjusts your working target in small, explainable steps."],["Can I track workouts too?","Yes. Log exercises, sets, reps, load, cardio, and reusable workout templates in the same app as your nutrition."],["Does it work for fat loss, maintenance, or muscle gain?","Yes. Your goal sets the direction; your actual trend helps refine the target. The same system works whether the intended rate is down, stable, or up."],["Is my data private?","Your account data is protected by authenticated access rules. CalStory does not use ads, and you can review the full details in the privacy policy."],["Can I use it on mobile?","Yes. CalStory is responsive and works in a mobile browser, so meals and workouts can be logged where they happen."]] as const;
export function PricingValue({signedIn}:{signedIn:boolean}){return <section className={styles.pricing} id="pricing"><Reveal className={styles.pricingCopy}><Eyebrow>PRICING</Eyebrow><h2>Start free. Upgrade when CalStory starts doing more for you.</h2><p>Core tracking stays useful on day one. Paid plans add deeper automation when your routine needs it.</p><Link href="/pricing" className={styles.textLink}>Compare every feature <ArrowRight size={14}/></Link></Reveal><Reveal className={styles.priceCard} delay={.06}><div className={styles.priceTop}><span>FREE</span><strong>$0 <small>forever</small></strong></div><ul><li><Check/>Meals, macros, and weight</li><li><Check/>Full workout logging</li><li><Check/>Progress dashboard</li></ul><PrimaryCta signedIn={signedIn}/><p>No credit card. No ads.</p></Reveal><Reveal className={`${styles.priceCard} ${styles.priceCardDark}`} delay={.12}><div className={styles.priceTop}><span>PLUS</span><strong>$7 <small>/ month</small></strong></div><ul><li><Check/>Everything in Free</li><li><Check/>Adaptive TDEE insights</li><li><Check/>Unlimited AI meal logs</li></ul><Link href="/pricing" className={styles.plusButton}>See paid plans <ArrowRight size={15}/></Link><p>Upgrade only when it earns its place.</p></Reveal></section>}
export function LandingFaq(){const[active,setActive]=useState<number|null>(0);return <section className={styles.faq} id="faq"><Reveal><Eyebrow>FAQ</Eyebrow><h2>Questions, answered plainly.</h2><p>What to know before your first log.</p></Reveal><div className={styles.faqList}>{faqs.map(([q,a],i)=><div className={styles.faqItem} key={q}><button aria-expanded={active===i} onClick={()=>setActive(active===i?null:i)}><span>{q}</span><motion.span animate={{rotate:active===i?180:0}} transition={{duration:.2,ease:"easeInOut"}}><ChevronDown/></motion.span></button><AnimatePresence initial={false}>{active===i&&<motion.div className={styles.answer} initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}} transition={{duration:.24,ease:[.4,0,.2,1]}}><p>{a}</p></motion.div>}</AnimatePresence></div>)}</div></section>}
export function FinalCta({signedIn}:{signedIn:boolean}){return <Reveal><section className={styles.finalCta}><div><Eyebrow>YOUR NEXT DATA POINT</Eyebrow><h2>Start with today.</h2><p>Log your meals, track your training, and let the bigger picture build from there.</p><PrimaryCta signedIn={signedIn}/></div><div className={styles.ctaData}><div><span>Today</span><strong>2,184</strong><small>calories logged</small></div><ArrowRight/><div><span>In time</span><strong>A clear trend</strong><small>built from your routine</small></div></div></section></Reveal>}
export function LandingFooter(){return <footer className={styles.footer}><div className={styles.footerTop}><div><Link href="/" className={styles.footerBrand}><BrandLogo className={styles.logo}/>CalStory</Link><p>Nutrition and training, understood together.</p></div><div className={styles.footerLinks}><div><strong>Product</strong><Link href="/pricing">Pricing</Link><Link href="/dashboard">Dashboard</Link><Link href="/tools/calorie-calculator">Calorie calculator</Link></div><div><strong>Company</strong><Link href="/about">About</Link><Link href="/blog">Blog</Link><Link href="/contact">Contact</Link></div><div><strong>Legal</strong><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/cookies">Cookies</Link></div></div></div><div className={styles.footerBottom}><span>© {new Date().getFullYear()} CalStory</span><a href="https://github.com/tanishenigma/CalStory" target="_blank" rel="noreferrer"><FaGithub/>Open source on GitHub</a></div></footer>}
