"use client";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowRight, BarChart3, Dumbbell, Minus, Repeat2, TrendingUp, Zap } from "lucide-react";
import { Eyebrow, Reveal } from "./shared";
import styles from "@/app/landing.module.css";
const comparisons=[["A target calculated once","A target refined by your weight trend",TrendingUp],["Meals in one app, workouts in another","Nutrition and training in one timeline",Dumbbell],["Raw numbers without context","The change, the driver, and what to do next",BarChart3],["Rebuilding the same logs every day","Saved meals and templates ready to reuse",Repeat2]] as const;
const cases=[["Strength","Meals and working sets finally live beside the same weekly trend.","4 sessions / week",Dumbbell],["Marathon training","See whether harder weeks are actually supported by what you eat.","42 km this week",TrendingUp],["Fat loss","A target that responds to trend—not one noisy weigh-in.","–0.4 kg / week",BarChart3],["Hybrid training","One log for lifting, cardio, food, and the recovery picture.","3 lifts + 2 runs",Zap],["Maintenance","Enough structure to stay consistent without making food a second job.","18 day trend",Repeat2]] as const;
export function Comparison(){return <section className={styles.comparison}><Reveal className={styles.sectionHeading}><Eyebrow>WHY CALSTORY</Eyebrow><h2>Built to show you what your numbers actually mean.</h2><p>Most trackers record your data. CalStory helps you understand it.</p></Reveal><div className={styles.comparisonRows}>{comparisons.map(([problem,solution,Icon],i)=><motion.div className={styles.comparisonRow} key={problem} initial={{opacity:0,y:14}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.45,delay:i*.06,ease:"easeOut"}}><div className={styles.problem}><Minus size={15}/>{problem}</div><ArrowRight className={styles.rowArrow} size={16}/><div className={styles.solution}><Icon size={17}/>{solution}</div></motion.div>)}</div></section>}
export function UseCaseRail(){const reduced=useReducedMotion();const items=reduced?cases:[...cases,...cases];return <section className={styles.reviews}><Reveal className={styles.sectionHeading}><Eyebrow>BUILT FOR REAL ROUTINES</Eyebrow><h2>Lifters, runners, and <em>everyone</em> in between.</h2><p>Different goals. The same clear way to stay on track.</p></Reveal><div className={styles.railViewport}><div className={reduced?styles.railStatic:styles.rail}>{items.map(([use,text,metric,Icon],i)=><article className={styles.reviewCard} key={`${use}-${i}`}><div className={styles.reviewTop}><span><Icon size={17}/></span>{use}</div><p>{text}</p><small>{metric}</small></article>)}</div></div><p className={styles.demoNote}>Use-case examples — not customer testimonials.</p></section>}
