"use client";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowRight, BarChart3, Dumbbell, Minus, Repeat2, TrendingUp } from "lucide-react";
import { Eyebrow, Reveal } from "./shared";
import styles from "@/app/landing.module.css";
const comparisons=[["A target calculated once","A target refined by your weight trend",TrendingUp],["Meals in one app, workouts in another","Nutrition and training in one timeline",Dumbbell],["Raw numbers without context","The change, the driver, and what to do next",BarChart3],["Rebuilding the same logs every day","Saved meals and templates ready to reuse",Repeat2]] as const;
const testimonials=[["Maya Chen","I finally stopped treating food and training like separate projects. Seeing both in one place makes my week much easier to follow.","Strength training · 4 sessions / week","MC"],["Jordan Brooks","Logging meals takes seconds, and the trend view gives me the context I was always missing from a basic calorie counter.","Marathon training · 42 km this week","JB"],["Priya Shah","The small target adjustments feel practical instead of dramatic. I can stay consistent without overreacting to one weigh-in.","Fat loss · –0.4 kg / week","PS"],["Ethan Cole","Having lifting, runs, food, and recovery notes together means I can spot what is actually affecting my performance.","Hybrid training · 3 lifts + 2 runs","EC"],["Noah Williams","It has enough structure to keep me honest, but it never makes tracking feel like a second job.","Maintenance · 18 day trend","NW"]] as const;
export function Comparison(){return <section className={styles.comparison}><Reveal className={styles.sectionHeading}><Eyebrow>WHY CALSTORY</Eyebrow><h2>Built to show you what your numbers actually mean.</h2><p>Most trackers record your data. CalStory helps you understand it.</p></Reveal><div className={styles.comparisonRows}>{comparisons.map(([problem,solution,Icon],i)=><motion.div className={styles.comparisonRow} key={problem} initial={{opacity:0,y:14}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.45,delay:i*.06,ease:"easeOut"}}><div className={styles.problem}><Minus size={15}/>{problem}</div><ArrowRight className={styles.rowArrow} size={16}/><div className={styles.solution}><Icon size={17}/>{solution}</div></motion.div>)}</div></section>}
export function UseCaseRail(){const reduced=useReducedMotion();const items=reduced?testimonials:[...testimonials,...testimonials];return <section className={styles.reviews}><Reveal className={styles.sectionHeading}><Eyebrow>WHAT PEOPLE ARE SAYING</Eyebrow><h2>Lifters, runners, and <em>everyone</em> in between.</h2><p>Real routines, less friction, and a clearer picture of what is working.</p></Reveal><div className={styles.railViewport}><div className={reduced?styles.railStatic:styles.rail}>{items.map(([name,text,metric,initials],i)=><article className={styles.reviewCard} key={`${name}-${i}`}><div className={styles.reviewTop}><span>{initials}</span><strong>{name}</strong></div><p>“{text}”</p><small>{metric}</small></article>)}</div></div></section>}
